name: kasifim_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_gen_runner: ^5.2.0

  #GOOGLE

  #Development

  json_serializable: ^6.6.1
  google_sign_in: ^6.0.2
  retrofit: ^4.0.1
  dio: ^5.1.1
  hive: ^2.2.3
  equatable: ^2.0.5
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1
  video_player: ^2.6.1
  readmore: ^2.2.0
  camera: ^0.10.5+2
  path_provider: ^2.0.15
  video_editor: ^2.4.0
  helpers: ^1.2.3
  fraction: ^5.0.0
  image_picker: ^0.8.8
  badges: ^3.1.1
  flutter_bloc: ^8.1.2
  awesome_dio_interceptor: ^1.0.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  bloc: ^8.1.1
  logger: ^1.4.0

  # local storage 
  isar: 3.0.5
  isar_flutter_libs: 3.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.8
  injectable_generator:  ^1.5.4
  freezed: ^2.3.0
  isar_generator: 3.0.5

flutter_gen:
  colors:
    inputs:
      - assets/colors.xml
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/videos/

  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Caveat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Caveat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Caveat-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
